def class_dictionary():
    class_dictionary = {'kit fox, Vulpes macrotis': "c",
                        'English setter': "c",
                        'Australian terrier': "c",
                        'grey whale, gray whale, devilfish, Eschrichtius gibbosus, Eschrichtius robustus': "c",
                        'lesser panda, red panda, panda, bear cat, cat bear, Ailurus fulgens': "c",
                        'Egyptian cat': "c",
                        'ibex, Capra ibex': "c",
                        'Persian cat': "c",
                        'cougar, puma, catamount, mountain lion, painter, panther, Felis concolor': "c",
                        'gazelle': "c",
                        'porcupine, hedgehog': "c",
                        'sea lion': "c",
                        'badger': "c",
                        'Great Dane': "c",
                        'Scottish deerhound, deerhound': "c",
                        'killer whale, killer, orca, grampus, sea wolf, Orcinus orca': "c",
                        'mink': "c",
                        'African elephant, Loxodonta africana': "c",
                        'red wolf, maned wolf, Canis rufus, Canis niger': "c",
                        'jaguar, panther, Panthera onca, Felis onca': "c",
                        'hyena, hyaena': "c",
                        'titi, titi monkey': "c",
                        'three-toed sloth, ai, Bradypus tridactylus': "c",
                        'sorrel': "c",
                        'black-footed ferret, ferret, Mustela nigripes': "c",
                        'dalmatian, coach dog, carriage dog': "c",
                        'Staffordshire bullterrier, Staffordshire bull terrier': "c",
                        'Bouvier des Flandres, Bouviers des Flandres': "c",
                        'weasel': "c",
                        'miniature poodle': "c",
                        'bighorn, bighorn sheep, cimarron, Rocky Mountain bighorn, Rocky Mountain sheep, Ovis canadensis': "c",
                        'fox squirrel, eastern fox squirrel, Sciurus niger': "c",
                        'colobus, colobus monkey': "c",
                        'tiger cat': "c",
                        'impala, Aepyceros melampus': "c",
                        'coyote, prairie wolf, brush wolf, Canis latrans': "c",
                        'Yorkshire terrier': "c",
                        'Newfoundland, Newfoundland dog': "c",
                        'red fox, Vulpes vulpes': "c",
                        'hartebeest': "c",
                        'grey fox, gray fox, Urocyon cinereoargenteus': "c",
                        'Pekinese, Pekingese, Peke': "c",
                        'guenon, guenon monkey': "c",
                        'mongoose': "c",
                        'indri, indris, Indri indri, Indri brevicaudatus': "c",
                        'tiger, Panthera tigris': "c",
                        'wild boar, boar, Sus scrofa': "c",
                        'zebra': "c",
                        'ram, tup': "c",
                        'orangutan, orang, orangutang, Pongo pygmaeus': "c",
                        'basenji': "c",
                        'leopard, Panthera pardus': "c",
                        'vizsla, Hungarian pointer': "c",
                        'squirrel monkey, Saimiri sciureus': "c",
                        'Siamese cat, Siamese': "c",
                        'chimpanzee, chimp, Pan troglodytes': "c",
                        'komondor': "c",
                        'proboscis monkey, Nasalis larvatus': "c",
                        'guinea pig, Cavia cobaya': "c",
                        'white wolf, Arctic wolf, Canis lupus tundrarum': "c",
                        'ice bear, polar bear, Ursus Maritimus, Thalarctos maritimus': "c",
                        'gorilla, Gorilla gorilla': "c",
                        'ox': "c",
                        'Tibetan mastiff': "c",
                        'spider monkey, Ateles geoffroyi': "c",
                        'Doberman, Doberman pinscher': "c",
                        'warthog': "c",
                        'Arabian camel, dromedary, Camelus dromedarius': "c",
                        'siamang, Hylobates syndactylus, Symphalangus syndactylus': "c",
                        'golden retriever': "c",
                        'Border collie': "c",
                        'hare': "c",
                        'boxer': "c",
                        'patas, hussar monkey, Erythrocebus patas': "c",
                        'baboon': "c",
                        'macaque': "c",
                        'capuchin, ringtail, Cebus capucinus': "c",
                        'flat-coated retriever': "c",
                        'hog, pig, grunter, squealer, Sus scrofa': "c",
                        'Eskimo dog, husky': "c",
                        'Brittany spaniel': "c",
                        'dial telephone, dial phone': "r",
                        'maze, labyrinth': "r",
                        'Gordon setter': "c",
                        'dingo, warrigal, warragal, Canis dingo': "c",
                        'hamster': "c",
                        'Arctic fox, white fox, Alopex lagopus': "c",
                        'water buffalo, water ox, Asiatic buffalo, Bubalus bubalis': "c",
                        'American black bear, black bear, Ursus americanus, Euarctos americanus': "c",
                        'Angora, Angora rabbit': "c",
                        'bison': "c",
                        'howler monkey, howler': "c",
                        'hippopotamus, hippo, river horse, Hippopotamus amphibius': "c",
                        'giant panda, panda, panda bear, coon bear, Ailuropoda melanoleuca': "c",
                        'tabby, tabby cat': "c",
                        'marmoset': "c",
                        'Saint Bernard, St Bernard': "c",
                        'armadillo': "c",
                        'redbone': "c",
                        'polecat, fitch, foulmart, foumart, Mustela putorius': "c",
                        'marmot': "c",
                        'gibbon, Hylobates lar': "c",
                        'llama': "c",
                        'wood rabbit, cottontail, cottontail rabbit': "c",
                        'lion, king of beasts, Panthera leo': "c",
                        'Irish setter, red setter': "c",
                        'dugong, Dugong dugon': "c",
                        'Indian elephant, Elephas maximus': "c",
                        'beaver': "c",
                        'Madagascar cat, ring-tailed lemur, Lemur catta': "c",
                        'Rhodesian ridgeback': "c",
                        'lynx, catamount': "c",
                        'African hunting dog, hyena dog, Cape hunting dog, Lycaon pictus': "c",
                        'langur': "c",
                        'timber wolf, grey wolf, gray wolf, Canis lupus': "c",
                        'cheetah, chetah, Acinonyx jubatus': "c",
                        'sloth bear, Melursus ursinus, Ursus ursinus': "c",
                        'German shepherd, German shepherd dog, German police dog, alsatian': "c",
                        'otter': "c",
                        'koala, koala bear, kangaroo bear, native bear, Phascolarctos cinereus': "c",
                        'tusker': "c",
                        'echidna, spiny anteater, anteater': "c",
                        'wallaby, brush kangaroo': "c",
                        'platypus, duckbill, duckbilled platypus, duck-billed platypus, Ornithorhynchus anatinus': "c",
                        'wombat': "c",
                        'revolver, six-gun, six-shooter': "r",
                        'umbrella': "r",
                        'schooner': "r",
                        'soccer ball': "r",
                        'accordion, piano accordion, squeeze box': "r",
                        'ant, emmet, pismire': "c",
                        'starfish, sea star': "c",
                        'chambered nautilus, pearly nautilus, nautilus': "r",
                        'grand piano, grand': "r",
                        'laptop, laptop computer': "r",
                        'strawberry': "c",
                        'airliner': "r",
                        'warplane, military plane': "r",
                        'airship, dirigible': "r",
                        'balloon': "r",
                        'space shuttle': "r",
                        'fireboat': "r",
                        'gondola': "r",
                        'speedboat': "r",
                        'lifeboat': "r",
                        'canoe': "r",
                        'yawl': "r",
                        'catamaran': "r",
                        'trimaran': "r",
                        'container ship, containership, container vessel': "r",
                        'liner, ocean liner': "r",
                        'pirate, pirate ship': "r",
                        'aircraft carrier, carrier, flattop, attack aircraft carrier': "r",
                        'submarine, pigboat, sub, U-boat': "r",
                        'wreck': "r",
                        'half track': "r",
                        'tank, army tank, armored combat vehicle, armoured combat vehicle': "r",
                        'missile': "r",
                        'bobsled, bobsleigh, bob': "r",
                        'dogsled, dog sled, dog sleigh': "r",
                        'bicycle-built-for-two, tandem bicycle, tandem': "r",
                        'mountain bike, all-terrain bike, off-roader': "r",
                        'freight car': "r",
                        'passenger car, coach, carriage': "r",
                        'barrow, garden cart, lawn cart, wheelbarrow': "r",
                        'shopping cart': "r",
                        'motor scooter, scooter': "r",
                        'forklift': "r",
                        'electric locomotive': "r",
                        'steam locomotive': "r",
                        'amphibian, amphibious vehicle': "r",
                        'ambulance': "r",
                        'beach wagon, station wagon, wagon, estate car, beach waggon, station waggon, waggon': "r",
                        'cab, hack, taxi, taxicab': "r",
                        'convertible': "r",
                        'jeep, landrover': "r",
                        'limousine, limo': "r",
                        'minivan': "r",
                        'Model T': "r",
                        'racer, race car, racing car': "r",
                        'sports car, sport car': "r",
                        'go-kart': "r",
                        'golfcart, golf cart': "r",
                        'moped': "r",
                        'snowplow, snowplough': "r",
                        'fire engine, fire truck': "r",
                        'garbage truck, dustcart': "r",
                        'pickup, pickup truck': "r",
                        'tow truck, tow car, wrecker': "r",
                        'trailer truck, tractor trailer, trucking rig, rig, articulated lorry, semi': "r",
                        'moving van': "r",
                        'police van, police wagon, paddy wagon, patrol wagon, wagon, black Maria': "r",
                        'recreational vehicle, RV, R.V.': "r",
                        'streetcar, tram, tramcar, trolley, trolley car': "r",
                        'snowmobile': "r",
                        'tractor': "r",
                        'mobile home, manufactured home': "r",
                        'tricycle, trike, velocipede': "r",
                        'unicycle, monocycle': "r",
                        'horse cart, horse-cart': "r",
                        'mosquito net': "r",
                        'oxcart': "r",
                        'bassinet': "r",
                        'cradle': "r",
                        'crib, cot': "r",
                        'four-poster': "r",
                        'bookcase': "r",
                        'china cabinet, china closet': "r",
                        'medicine chest, medicine cabinet': "r",
                        'chiffonier, commode': "r",
                        'table lamp': "r",
                        'file, file cabinet, filing cabinet': "r",
                        'pay-phone, pay-station': "r",
                        'park bench': "r",
                        'barber chair': "r",
                        'throne': "r",
                        'folding chair': "r",
                        'rocking chair, rocker': "r",
                        'studio couch, day bed': "r",
                        'toilet seat': "r",
                        'desk': "r",
                        'pool table, billiard table, snooker table': "r",
                        'dining table, board': "r",
                        'entertainment center': "r",
                        'wardrobe, closet, press': "r",
                        'Granny Smith': "c",
                        'orange': "c",
                        'lemon': "c",
                        'fig': "c",
                        'pineapple, ananas': "c",
                        'banana': "c",
                        'jackfruit, jak, jack': "c",
                        'custard apple': "c",
                        'pomegranate': "c",
                        'acorn': "c",
                        'hip, rose hip, rosehip': "c",
                        'ear, spike, capitulum': "c",
                        'rapeseed': "c",
                        'corn': "c",
                        'buckeye, horse chestnut, conker': "c",
                        'organ, pipe organ': "r",
                        'upright, upright piano': "r",
                        'chime, bell, gong': "r",
                        'drum, membranophone, tympan': "r",
                        'gong, tam-tam': "r",
                        'maraca': "r",
                        'marimba, xylophone': "r",
                        'steel drum': "r",
                        'banjo': "r",
                        'cello, violoncello': "r",
                        'lampshade, lamp shade': "r",
                        'harp': "r",
                        'acoustic guitar': "r",
                        'electric guitar': "r",
                        'cornet, horn, trumpet, trump': "r",
                        'French horn, horn': "r",
                        'trombone': "r",
                        'harmonica, mouth organ, harp, mouth harp': "r",
                        'ocarina, sweet potato': "r",
                        'panpipe, pandean pipe, syrinx': "r",
                        'bassoon': "r",
                        'sax, saxophone': "r",
                        'flute, transverse flute': "r",
                        'daisy': "c",
                        "yellow lady's slipper, yellow lady-slipper, Cypripedium calceolus, Cypripedium parviflorum": "c",
                        'cliff, drop, drop-off': "r",
                        'valley, vale': "r",
                        'alp': "r",
                        'volcano': "r",
                        'promontory, headland, head, foreland': "r",
                        'sandbar, sand bar': "r",
                        'coral reef': "c",
                        'lakeside, lakeshore': "r",
                        'seashore, coast, seacoast, sea-coast': "r",
                        'geyser': "r",
                        'hatchet': "r",
                        'cleaver, meat cleaver, chopper': "r",
                        'letter opener, paper knife, paperknife': "r",
                        "plane, carpenter's plane, woodworking plane": "r",
                        'power drill': "r",
                        'lawn mower, mower': "r",
                        'hammer': "r",
                        'corkscrew, bottle screw': "r",
                        'can opener, tin opener': "r",
                        "plunger, plumber's helper": "r",
                        'screwdriver': "r",
                        'shovel': "r",
                        'plow, plough': "r",
                        'chain saw, chainsaw': "r",
                        'cock': "c",
                        'hen': "c",
                        'ostrich, Struthio camelus': "c",
                        'brambling, Fringilla montifringilla': "c",
                        'goldfinch, Carduelis carduelis': "c",
                        'house finch, linnet, Carpodacus mexicanus': "c",
                        'junco, snowbird': "c",
                        'indigo bunting, indigo finch, indigo bird, Passerina cyanea': "c",
                        'robin, American robin, Turdus migratorius': "c",
                        'bulbul': "c",
                        'jay': "c",
                        'magpie': "c",
                        'chickadee': "c",
                        'water ouzel, dipper': "c",
                        'kite': "r",
                        'bald eagle, American eagle, Haliaeetus leucocephalus': "c",
                        'vulture': "c",
                        'great grey owl, great gray owl, Strix nebulosa': "c",
                        'black grouse': "c",
                        'ptarmigan': "c",
                        'ruffed grouse, partridge, Bonasa umbellus': "c",
                        'prairie chicken, prairie grouse, prairie fowl': "c",
                        'peacock': "c",
                        'quail': "c",
                        'partridge': "c",
                        'African grey, African gray, Psittacus erithacus': "c",
                        'macaw': "c",
                        'sulphur-crested cockatoo, Kakatoe galerita, Cacatua galerita': "c",
                        'lorikeet': "c",
                        'coucal': "c",
                        'bee eater': "c",
                        'hornbill': "c",
                        'hummingbird': "c",
                        'jacamar': "c",
                        'toucan': "c",
                        'drake': "c",
                        'red-breasted merganser, Mergus serrator': "c",
                        'goose': "c",
                        'black swan, Cygnus atratus': "c",
                        'white stork, Ciconia ciconia': "c",
                        'black stork, Ciconia nigra': "c",
                        'spoonbill': "c",
                        'flamingo': "c",
                        'American egret, great white heron, Egretta albus': "c",
                        'little blue heron, Egretta caerulea': "c",
                        'bittern': "c",
                        'crane': "c",
                        'limpkin, Aramus pictus': "c",
                        'American coot, marsh hen, mud hen, water hen, Fulica americana': "c",
                        'bustard': "c",
                        'ruddy turnstone, Arenaria interpres': "c",
                        'red-backed sandpiper, dunlin, Erolia alpina': "c",
                        'redshank, Tringa totanus': "c",
                        'dowitcher': "c",
                        'oystercatcher, oyster catcher': "c",
                        'European gallinule, Porphyrio porphyrio': "c",
                        'pelican': "c",
                        'king penguin, Aptenodytes patagonica': "c",
                        'albatross, mollymawk': "c",
                        'great white shark, white shark, man-eater, man-eating shark, Carcharodon carcharias': "c",
                        'tiger shark, Galeocerdo cuvieri': "c",
                        'hammerhead, hammerhead shark': "c",
                        'electric ray, crampfish, numbfish, torpedo': "c",
                        'stingray': "c",
                        'barracouta, snoek': "c",
                        'coho, cohoe, coho salmon, blue jack, silver salmon, Oncorhynchus kisutch': "c",
                        'tench, Tinca tinca': "c",
                        'goldfish, Carassius auratus': "c",
                        'eel': "c",
                        'rock beauty, Holocanthus tricolor': "c",
                        'anemone fish': "c",
                        'lionfish': "c",
                        'puffer, pufferfish, blowfish, globefish': "c",
                        'sturgeon': "c",
                        'gar, garfish, garpike, billfish, Lepisosteus osseus': "c",
                        'loggerhead, loggerhead turtle, Caretta caretta': "c",
                        'mud turtle': "c",
                        'terrapin': "c",
                        'box turtle, box tortoise': "c",
                        'banded gecko': "c",
                        'common iguana, iguana, Iguana iguana': "c",
                        'American chameleon, anole, Anolis carolinensis': "c",
                        'whiptail, whiptail lizard': "c",
                        'agama': "c",
                        'frilled lizard, Chlamydosaurus kingi': "c",
                        'alligator lizard': "c",
                        'Gila monster, Heloderma suspectum': "c",
                        'green lizard, Lacerta viridis': "c",
                        'African chameleon, Chamaeleo chamaeleon': "c",
                        'Komodo dragon, Komodo lizard, dragon lizard, giant lizard, Varanus komodoensis': "c",
                        'triceratops': "c",
                        'African crocodile, Nile crocodile, Crocodylus niloticus': "c",
                        'American alligator, Alligator mississipiensis': "c",
                        'thunder snake, worm snake, Carphophis amoenus': "c",
                        'ringneck snake, ring-necked snake, ring snake': "c",
                        'hognose snake, puff adder, sand viper': "c",
                        'green snake, grass snake': "c",
                        'king snake, kingsnake': "c",
                        'garter snake, grass snake': "c",
                        'water snake': "c",
                        'vine snake': "c",
                        'night snake, Hypsiglena torquata': "c",
                        'boa constrictor, Constrictor constrictor': "c",
                        'rock python, rock snake, Python sebae': "c",
                        'Indian cobra, Naja naja': "c",
                        'green mamba': "c",
                        'sea snake': "c",
                        'horned viper, cerastes, sand viper, horned asp, Cerastes cornutus': "c",
                        'stone wall': "c",
                        'sidewinder, horned rattlesnake, Crotalus cerastes': "c",
                        'European fire salamander, Salamandra salamandra': "c",
                        'common newt, Triturus vulgaris': "c",
                        'eft': "c",
                        'spotted salamander, Ambystoma maculatum': "c",
                        'axolotl, mud puppy, Ambystoma mexicanum': "c",
                        'bullfrog, Rana catesbeiana': "c",
                        'tree frog, tree-frog': "c",
                        'tailed frog, bell toad, ribbed toad, tailed toad, Ascaphus trui': "c",
                        'whistle': "r",
                        'wing': "r",
                        'paintbrush': "r",
                        'oxygen mask': "r",
                        'snorkel': "r",
                        'loudspeaker, speaker, speaker unit, loudspeaker system, speaker system': "r",
                        'microphone, mike': "r",
                        'screen, CRT screen': "r",
                        'mouse, computer mouse': "r",
                        'electric fan, blower': "r",
                        'oil filter': "r",
                        'strainer': "r",
                        'space heater': "r",
                        'stove': "r",
                        'guillotine': "r",
                        'barometer': "r",
                        'rule, ruler': "r",
                        'odometer, hodometer, mileometer, milometer': "r",
                        'scale, weighing machine': "r",
                        'analog clock': "r",
                        'digital clock': "r",
                        'wall clock': "r",
                        'hourglass': "r",
                        'sundial': "r",
                        'parking meter': "r",
                        'stopwatch, stop watch': "r",
                        'digital watch': "r",
                        'stethoscope': "r",
                        'syringe': "r",
                        'magnetic compass': "r",
                        'binoculars, field glasses, opera glasses': "r",
                        'projector': "r",
                        'sunglasses, dark glasses, shades': "r",
                        "loupe, jeweler's loupe": "r",
                        'radio telescope, radio reflector': "r",
                        'bow': "r",
                        'cannon': "r",
                        'assault rifle, assault gun': "r",
                        'rifle': "r",
                        'projectile, missile': "r",
                        'computer keyboard, keypad': "r",
                        'typewriter keyboard': "r",
                        'crane': "r",
                        'lighter, light, igniter, ignitor': "r",
                        'abacus': "r",
                        'cash machine, cash dispenser, automated teller machine, automatic teller machine, automated teller, automatic teller, ATM': "r",
                        'slide rule, slipstick': "r",
                        'desktop computer': "r",
                        'hand-held computer, hand-held microcomputer': "r",
                        'notebook, notebook computer': "r",
                        'padlock': "r",
                        'harvester, reaper': "r",
                        'thresher, thrasher, threshing machine': "r",
                        'printer': "r",
                        'slot, one-armed bandit': "r",
                        'vending machine': "r",
                        'sewing machine': "r",
                        'joystick': "r",
                        'switch, electric switch, electrical switch': "r",
                        'hook, claw': "r",
                        'car wheel': "r",
                        'paddlewheel, paddle wheel': "r",
                        'pinwheel': "r",
                        "potter's wheel": "r",
                        'gas pump, gasoline pump, petrol pump, island dispenser': "r",
                        'carousel, carrousel, merry-go-round, roundabout, whirligig': "r",
                        'swing': "r",
                        'reel': "r",
                        'radiator': "r",
                        'puck, hockey puck': "r",
                        'hard disc, hard disk, fixed disk': "r",
                        'sunglass': "r",
                        'pick, plectrum, plectron': "r",
                        'car mirror': "r",
                        'solar dish, solar collector, solar furnace': "r",
                        'remote control, remote': "r",
                        'disk brake, disc brake': "r",
                        'buckle': "r",
                        'hair slide': "r",
                        'knot': "r",
                        'combination lock': "r",
                        'web site, website, internet site, site': "r",
                        'nail': "r",
                        'safety pin': "r",
                        'screw': "r",
                        'muzzle': "r",
                        'seat belt, seatbelt': "r",
                        'ski': "r",
                        'candle, taper, wax light': "r",
                        "jack-o'-lantern": "r",
                        'spotlight, spot': "r",
                        'torch': "r",
                        'neck brace': "r",
                        'pier': "r",
                        'tripod': "r",
                        'maypole': "r",
                        'hand blower, blow dryer, blow drier, hair dryer, hair drier': "r",
                        'mousetrap': "r",
                        "spider web, spider's web": "c",
                        'trilobite': "c",
                        'harvestman, daddy longlegs, Phalangium opilio': "c",
                        'scorpion': "c",
                        'black and gold garden spider, Argiope aurantia': "c",
                        'barn spider, Araneus cavaticus': "c",
                        'garden spider, Aranea diademata': "c",
                        'black widow, Latrodectus mactans': "c",
                        'tarantula': "c",
                        'wolf spider, hunting spider': "c",
                        'tick': "c",
                        'centipede': "c",
                        'isopod': "c",
                        'Dungeness crab, Cancer magister': "c",
                        'rock crab, Cancer irroratus': "c",
                        'fiddler crab': "c",
                        'king crab, Alaska crab, Alaskan king crab, Alaska king crab, Paralithodes camtschatica': "c",
                        'American lobster, Northern lobster, Maine lobster, Homarus americanus': "c",
                        'spiny lobster, langouste, rock lobster, crawfish, crayfish, sea crawfish': "c",
                        'crayfish, crawfish, crawdad, crawdaddy': "c",
                        'hermit crab': "c",
                        'tiger beetle': "c",
                        'ladybug, ladybeetle, lady beetle, ladybird, ladybird beetle': "c",
                        'ground beetle, carabid beetle': "c",
                        'long-horned beetle, longicorn, longicorn beetle': "c",
                        'leaf beetle, chrysomelid': "c",
                        'dung beetle': "c",
                        'rhinoceros beetle': "c",
                        'weevil': "c",
                        'fly': "c",
                        'bee': "c",
                        'grasshopper, hopper': "c",
                        'cricket': "c",
                        'walking stick, walkingstick, stick insect': "c",
                        'cockroach, roach': "c",
                        'mantis, mantid': "c",
                        'cicada, cicala': "c",
                        'leafhopper': "c",
                        'lacewing, lacewing fly': "c",
                        "dragonfly, darning needle, devil's darning needle, sewing needle, snake feeder, snake doctor, mosquito hawk, skeeter hawk": "c",
                        'damselfly': "c",
                        'admiral': "c",
                        'ringlet, ringlet butterfly': "c",
                        'monarch, monarch butterfly, milkweed butterfly, Danaus plexippus': "c",
                        'cabbage butterfly': "c",
                        'sulphur butterfly, sulfur butterfly': "c",
                        'lycaenid, lycaenid butterfly': "c",
                        'jellyfish': "c",
                        'sea anemone, anemone': "c",
                        'brain coral': "c",
                        'flatworm, platyhelminth': "c",
                        'nematode, nematode worm, roundworm': "c",
                        'conch': "c",
                        'snail': "c",
                        'slug': "c",
                        'sea slug, nudibranch': "c",
                        'chiton, coat-of-mail shell, sea cradle, polyplacophore': "c",
                        'sea urchin': "c",
                        'sea cucumber, holothurian': "c",
                        'iron, smoothing iron': "r",
                        'espresso maker': "r",
                        'microwave, microwave oven': "r",
                        'Dutch oven': "r",
                        'rotisserie': "r",
                        'toaster': "r",
                        'waffle iron': "r",
                        'vacuum, vacuum cleaner': "r",
                        'dishwasher, dish washer, dishwashing machine': "r",
                        'refrigerator, icebox': "r",
                        'washer, automatic washer, washing machine': "r",
                        'Crock Pot': "r",
                        'frying pan, frypan, skillet': "r",
                        'wok': "r",
                        'caldron, cauldron': "r",
                        'coffeepot': "r",
                        'teapot': "r",
                        'spatula': "r",
                        'altar': "r",
                        'triumphal arch': "r",
                        'patio, terrace': "r",
                        'steel arch bridge': "r",
                        'suspension bridge': "r",
                        'viaduct': "r",
                        'barn': "r",
                        'greenhouse, nursery, glasshouse': "r",
                        'palace': "r",
                        'monastery': "r",
                        'library': "r",
                        'apiary, bee house': "r",
                        'boathouse': "r",
                        'church, church building': "r",
                        'mosque': "r",
                        'stupa, tope': "r",
                        'planetarium': "r",
                        'restaurant, eating house, eating place, eatery': "r",
                        'cinema, movie theater, movie theatre, movie house, picture palace': "r",
                        'home theater, home theatre': "r",
                        'lumbermill, sawmill': "r",
                        'coil, spiral, volute, whorl, helix': "r",
                        'obelisk': "r",
                        'totem pole': "r",
                        'castle': "r",
                        'prison, prison house': "r",
                        'grocery store, grocery, food market, market': "r",
                        'bakery, bakeshop, bakehouse': "r",
                        'barbershop': "r",
                        'bookshop, bookstore, bookstall': "r",
                        'butcher shop, meat market': "r",
                        'confectionery, confectionary, candy store': "r",
                        'shoe shop, shoe-shop, shoe store': "r",
                        'tobacco shop, tobacconist shop, tobacconist': "r",
                        'toyshop': "r",
                        'fountain': "r",
                        'cliff dwelling': "r",
                        'yurt': "r",
                        'dock, dockage, docking facility': "r",
                        'brass, memorial tablet, plaque': "r",
                        'megalith, megalithic structure': "r",
                        'bannister, banister, balustrade, balusters, handrail': "r",
                        'breakwater, groin, groyne, mole, bulwark, seawall, jetty': "r",
                        'dam, dike, dyke': "r",
                        'chainlink fence': "r",
                        'picket fence, paling': "r",
                        'worm fence, snake fence, snake-rail fence, Virginia fence': "r",
                        'diamondback, diamondback rattlesnake, Crotalus adamanteus': "r",
                        'grille, radiator grille': "r",
                        'sliding door': "r",
                        'turnstile': "r",
                        'mountain tent': "r",
                        'scoreboard': "r",
                        'honeycomb': "r",
                        'plate rack': "r",
                        'pedestal, plinth, footstall': "r",
                        'beacon, lighthouse, beacon light, pharos': "r",
                        'leatherback turtle, leatherback, leathery turtle, Dermochelys coriacea': "c",
                        'mashed potato': "c",
                        'bell pepper': "c",
                        'head cabbage': "c",
                        'broccoli': "c",
                        'cauliflower': "c",
                        'zucchini, courgette': "c",
                        'spaghetti squash': "c",
                        'acorn squash': "c",
                        'butternut squash': "c",
                        'cucumber, cuke': "c",
                        'artichoke, globe artichoke': "c",
                        'cardoon': "c",
                        'mushroom': "c",
                        'shower curtain': "r",
                        'jean, blue jean, denim': "r",
                        'carton': "r",
                        'handkerchief, hankie, hanky, hankey': "r",
                        'sandal': "r",
                        'ashcan, trash can, garbage can, wastebin, ash bin, ash-bin, ashbin, dustbin, trash barrel, trash bin': "r",
                        'safe': "r",
                        'plate': "r",
                        'necklace': "r",
                        'croquet ball': "r",
                        'fur coat': "r",
                        'thimble': "r",
                        "pajama, pyjama, pj's, jammies": "r",
                        'running shoe': "r",
                        'oboe, hautboy, hautbois': "r",
                        'cocktail shaker': "r",
                        'chest': "r",
                        'manhole cover': "r",
                        'modem': "r",
                        'tub, vat': "r",
                        'tray': "r",
                        'balance beam, beam': "r",
                        'bagel, beigel': "c",
                        'violin, fiddle': "r",
                        'prayer rug, prayer mat': "r",
                        'kimono': "r",
                        'hot pot, hotpot': "r",
                        'whiskey jug': "r",
                        'knee pad': "r",
                        'book jacket, dust cover, dust jacket, dust wrapper': "r",
                        'spindle': "r",
                        'ski mask': "r",
                        'beer bottle': "r",
                        'crash helmet': "r",
                        'bottlecap': "r",
                        'tile roof': "r",
                        'mask': "r",
                        'maillot': "r",
                        'Petri dish': "r",
                        'football helmet': "r",
                        'bathing cap, swimming cap': "r",
                        'teddy, teddy bear': "r",
                        'holster': "r",
                        'pop bottle, soda bottle': "r",
                        'photocopier': "r",
                        'vestment': "r",
                        'crossword puzzle, crossword': "r",
                        'golf ball': "r",
                        'trifle': "r",
                        'suit, suit of clothes': "r",
                        'water tower': "r",
                        'feather boa, boa': "r",
                        'cloak': "r",
                        'red wine': "r",
                        'drumstick': "r",
                        'shield, buckler': "r",
                        'Christmas stocking': "r",
                        'hoopskirt, crinoline': "r",
                        'menu': "r",
                        'stage': "r",
                        'bonnet, poke bonnet': "r",
                        'meat loaf, meatloaf': "c",
                        'baseball': "r",
                        'face powder': "r",
                        'scabbard': "r",
                        'sunscreen, sunblock, sun blocker': "r",
                        'beer glass': "r",
                        'hen-of-the-woods, hen of the woods, Polyporus frondosus, Grifola frondosa': "c",
                        'guacamole': "c",
                        'wool, woolen, woollen': "r",
                        'hay': "c",
                        'bow tie, bow-tie, bowtie': "r",
                        'mailbag, postbag': "r",
                        'water jug': "r",
                        'bucket, pail': "r",
                        'dishrag, dishcloth': "r",
                        'soup bowl': "r",
                        'eggnog': "c",
                        'mortar': "r",
                        'trench coat': "r",
                        'paddle, boat paddle': "r",
                        'chain': "r",
                        'swab, swob, mop': "r",
                        'mixing bowl': "r",
                        'potpie': "c",
                        'wine bottle': "r",
                        'shoji': "r",
                        'bulletproof vest': "r",
                        'drilling platform, offshore rig': "r",
                        'binder, ring-binder': "r",
                        'cardigan': "r",
                        'sweatshirt': "r",
                        'pot, flowerpot': "r",
                        'birdhouse': "r",
                        'jinrikisha, ricksha, rickshaw': "r",
                        'hamper': "r",
                        'ping-pong ball': "r",
                        'pencil box, pencil case': "r",
                        'consomme': "r",
                        'apron': "r",
                        'punching bag, punch bag, punching ball, punchball': "r",
                        'backpack, back pack, knapsack, packsack, rucksack, haversack': "r",
                        'groom, bridegroom': "r",
                        'bearskin, busby, shako': "r",
                        'pencil sharpener': "r",
                        'broom': "r",
                        'abaya': "r",
                        'mortarboard': "r",
                        'poncho': "r",
                        'crutch': "r",
                        'Polaroid camera, Polaroid Land camera': "r",
                        'space bar': "r",
                        'cup': "r",
                        'racket, racquet': "r",
                        'traffic light, traffic signal, stoplight': "r",
                        'quill, quill pen': "r",
                        'radio, wireless': "r",
                        'snow leopard, ounce, Panthera uncia': "c",
                        'dough': "c",
                        'cuirass': "r",
                        'military uniform': "r",
                        'lipstick, lip rouge': "r",
                        'shower cap': "r",
                        'monitor': "r",
                        'oscilloscope, scope, cathode-ray oscilloscope, CRO': "r",
                        'mitten': "r",
                        'brassiere, bra, bandeau': "r",
                        'French loaf': "c",
                        'vase': "r",
                        'milk can': "r",
                        'rugby ball': "r",
                        'paper towel': "r",
                        'earthstar': "r",
                        'envelope': "r",
                        'miniskirt, mini': "r",
                        'cowboy hat, ten-gallon hat': "r",
                        'trolleybus, trolley coach, trackless trolley': "r",
                        'perfume, essence': "r",
                        'bathtub, bathing tub, bath, tub': "r",
                        'hotdog, hot dog, red hot': "c",
                        'coral fungus': "c",
                        'bullet train, bullet': "r",
                        'pillow': "r",
                        'toilet tissue, toilet paper, bathroom tissue': "r",
                        'cassette': "r",
                        "carpenter's kit, tool kit": "r",
                        'ladle': "r",
                        'stinkhorn, carrion fungus': "r",
                        'lotion': "r",
                        'hair spray': "r",
                        "academic gown, academic robe, judge's robe": "r",
                        'dome': "r",
                        'crate': "r",
                        'wig': "r",
                        'burrito': "c",
                        'pill bottle': "r",
                        'chain mail, ring mail, mail, chain armor, chain armour, ring armor, ring armour': "r",
                        'theater curtain, theatre curtain': "r",
                        'window shade': "r",
                        'barrel, cask': "r",
                        'washbasin, handbasin, washbowl, lavabo, wash-hand basin': "r",
                        'ballpoint, ballpoint pen, ballpen, Biro': "r",
                        'basketball': "r",
                        'bath towel': "r",
                        'cowboy boot': "r",
                        'gown': "r",
                        'window screen': "r",
                        'agaric': "r",
                        'standard poodle': "r",
                        'cellular telephone, cellular phone, cellphone, cell, mobile phone': "r",
                        'nipple': "r",
                        'barbell': "r",
                        'mailbox, letter box': "r",
                        'lab coat, laboratory coat': "r",
                        'fire screen, fireguard': "r",
                        'minibus': "r",
                        'packet': "r",
                        'brown bear, bruin, Ursus arctos': "r",
                        'pole': "r",
                        'horizontal bar, high bar': "r",
                        'sombrero': "r",
                        'pickelhaube': "r",
                        'rain barrel': "r",
                        'wallet, billfold, notecase, pocketbook': "r",
                        'cassette player': "r",
                        'comic book': "r",
                        'piggy bank, penny bank': "r",
                        'street sign': "r",
                        'bell cote, bell cot': "r",
                        'fountain pen': "r",
                        'Windsor tie': "r",
                        'volleyball': "r",
                        'overskirt': "r",
                        'sarong': "r",
                        'purse': "r",
                        'bolo tie, bolo, bola tie, bola': "r",
                        'bib': "r",
                        'parachute, chute': "r",
                        'sleeping bag': "r",
                        'television, television system': "r",
                        'swimming trunks, bathing trunks': "r",
                        'measuring cup': "r",
                        'espresso': "c",
                        'pizza, pizza pie': "c",
                        'breastplate, aegis, egis': "r",
                        'shopping basket': "r",
                        'wooden spoon': "r",
                        'saltshaker, salt shaker': "r",
                        'chocolate sauce, chocolate syrup': "c",
                        'ballplayer, baseball player': "r",
                        'goblet': "r",
                        'gyromitra': "r",
                        'stretcher': "r",
                        'water bottle': "r",
                        'skunk, polecat, wood pussy': "c",
                        'soap dispenser': "r",
                        'jersey, T-shirt, tee shirt': "r",
                        'school bus': "r",
                        'jigsaw puzzle': "r",
                        'plastic bag': "r",
                        'reflex camera': "r",
                        'diaper, nappy, napkin': "r",
                        'Band Aid': "r",
                        'ice lolly, lolly, lollipop, popsicle': "r",
                        'velvet': "r",
                        'tennis ball': "r",
                        'gasmask, respirator, gas helmet': "r",
                        'doormat, welcome mat': "r",
                        'Loafer': "r",
                        'ice cream, icecream': "c",
                        'pretzel': "c",
                        'quilt, comforter, comfort, puff': "r",
                        'maillot, tank suit': "r",
                        'tape player': "r",
                        'clog, geta, patten, sabot': "r",
                        'iPod': "r",
                        'bolete': "r",
                        'meerkat, mierkat': "c",
                        'scuba diver': "r",
                        'pitcher, ewer': "r",
                        'matchstick': "r",
                        'bikini, two-piece': "r",
                        'sock': "r",
                        'CD player': "r",
                        'lens cap, lens cover': "r",
                        'thatch, thatched roof': "r",
                        'vault': "r",
                        'beaker': "r",
                        'bubble': "r",
                        'cheeseburger': "c",
                        'parallel bars, bars': "r",
                        'flagpole, flagstaff': "r",
                        'coffee mug': "r",
                        'rubber eraser, rubber, pencil eraser': "r",
                        'stole': "r",
                        'carbonara': "r",
                        'dumbbell': "r",
                        'Siberian husky': "c",
                        'English springer, English springer spaniel': "c",
                        'malamute, malemute, Alaskan malamute': "c",
                        'Walker hound, Walker foxhound': "c",
                        'Welsh springer spaniel': "c",
                        'whippet': "c",
                        'Weimaraner': "c",
                        'soft-coated wheaten terrier': "c",
                        'Dandie Dinmont, Dandie Dinmont terrier': "c",
                        'Old English sheepdog, bobtail': "c",
                        'otterhound, otter hound': "c",
                        'bloodhound, sleuthhound': "c",
                        'Airedale, Airedale terrier': "c",
                        'giant schnauzer': "c",
                        'black-and-tan coonhound': "c",
                        'papillon': "c",
                        'Mexican hairless': "c",
                        'Cardigan, Cardigan Welsh corgi': "c",
                        'malinois': "c",
                        'Lhasa, Lhasa apso': "c",
                        'Norwegian elkhound, elkhound': "c",
                        'Rottweiler': "c",
                        'Saluki, gazelle hound': "c",
                        'schipperke': "c",
                        'Brabancon griffon': "c",
                        'West Highland white terrier': "c",
                        'Sealyham terrier, Sealyham': "c",
                        'Irish wolfhound': "c",
                        'EntleBucher': "c",
                        'French bulldog': "c",
                        'Bernese mountain dog': "c",
                        'Maltese dog, Maltese terrier, Maltese': "c",
                        'Norfolk terrier': "c",
                        'toy terrier': "c",
                        'cairn, cairn terrier': "c",
                        'groenendael': "c",
                        'clumber, clumber spaniel': "c",
                        'Afghan hound, Afghan': "c",
                        'Japanese spaniel': "c",
                        'borzoi, Russian wolfhound': "c",
                        'toy poodle': "c",
                        'Kerry blue terrier': "c",
                        'Scotch terrier, Scottish terrier, Scottie': "c",
                        'Boston bull, Boston terrier': "c",
                        'Greater Swiss Mountain dog': "c",
                        'Appenzeller': "c",
                        'Shih-Tzu': "c",
                        'Irish water spaniel': "c",
                        'Pomeranian': "c",
                        'Bedlington terrier': "c",
                        'miniature schnauzer': "c",
                        'collie': "c",
                        'Irish terrier': "c",
                        'affenpinscher, monkey pinscher, monkey dog': "c",
                        'silky terrier, Sydney silky': "c",
                        'beagle': "c",
                        'Leonberg': "c",
                        'German short-haired pointer': "c",
                        'dhole, Cuon alpinus': "c",
                        'Chesapeake Bay retriever': "c",
                        'bull mastiff': "c",
                        'kuvasz': "c",
                        'pug, pug-dog': "c",
                        'curly-coated retriever': "c",
                        'Norwich terrier': "c",
                        'keeshond': "c",
                        'Lakeland terrier': "c",
                        'standard schnauzer': "c",
                        'Tibetan terrier, chrysanthemum dog': "c",
                        'wire-haired fox terrier': "c",
                        'basset, basset hound': "c",
                        'chow, chow chow': "c",
                        'American Staffordshire terrier, Staffordshire terrier, American pit bull terrier, pit bull terrier': "c",
                        'Shetland sheepdog, Shetland sheep dog, Shetland': "c",
                        'Great Pyrenees': "c",
                        'Chihuahua': "c",
                        'Labrador retriever': "c",
                        'Samoyed, Samoyede': "c",
                        'bluetick': "c",
                        'kelpie': "c",
                        'miniature pinscher': "c",
                        'Italian greyhound': "c",
                        'cocker spaniel, English cocker spaniel, cocker': "c",
                        'Sussex spaniel': "c",
                        'Pembroke, Pembroke Welsh corgi': "c",
                        'Blenheim spaniel': "c",
                        'Ibizan hound, Ibizan Podenco': "c",
                        'English foxhound': "c",
                        'briard': "c",
                        'Border terrier': "c"}
    return class_dictionary